<a href="https://colab.research.google.com/github/siyab8160-max/Data-Science/blob/main/Data_Science_06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import pandas as pd

dct={
    'name':['Tom','Nick','Krish','Jack'],
    'age':[20,21,19,18],
    'roll':[1,2,3,4]
}

df= pd.DataFrame(dct)
print(df) #string format
df # this also prints

df1=pd.DataFrame(dct)
df1 # displays only once though we tried to print df & df1 both

#so now, we'll use the function
display(df)
display(df1)



# INDEXING
df=pd.DataFrame(dct,index=['a','b','c','d'])
display(df)

    name  age  roll
0    Tom   20     1
1   Nick   21     2
2  Krish   19     3
3   Jack   18     4

    name  age  roll
0    Tom   20     1
1   Nick   21     2
2  Krish   19     3
3   Jack   18     4

    name  age  roll
0    Tom   20     1
1   Nick   21     2
2  Krish   19     3
3   Jack   18     4

    name  age  roll
a    Tom   20     1
b   Nick   21     2
c  Krish   19     3
d   Jack   18     4

In [10]:
#CSV FILE
df=pd.read_csv('student_data.csv')
display(df.head()) #-> gives the first five values

#parameter can also be passed in this function
display(df.head(7))

display(df.tail())

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
5,7,40,9,10,0,60,72.33,Placed
6,10,40,4,11,9,50,98.12,Placed

In [11]:
df.shape #->(rows,columns)

(10000, 8)

In [ ]:
#EVERY FILE CAN BE READ AND THERE IS FUNTION TO DO THIS

In [12]:
# Meta Data ->data about data like the format /type of the data, number of columns, type of data in columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   study_hours            10000 non-null  int64
 1   attendance             10000 non-null  int64
 2   sleep_hours            10000 non-null  int64
 3   internet_usage         10000 non-null  int64
 4   assignments_completed  10000 non-null  int64
 5   previous_score         10000 non-null  int64
 6   exam_score             10000 non-null  float64
 7   placement_status       10000 non-null  object
dtypes: float64(1), int64(6), object(1)
memory usage: 625.1+ KB

In [14]:
df=pd.read_csv('student_data.csv')
df.describe()
#horizontal bar : column names
# QUARTILES : q1, q2, q3
# q1 -> 25% ->  median of first half from 0 to q2
# q2 -> 50% -> median
# q3 -> 75% -> median of second half from q2 to n
# IQR -> INTER QUARTILE RANGE : q3 - q1

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score
count,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000
mean,5.989600,69.88460,6.498500,6.062600,9.988400,64.91100,86.704207
std,3.163589,17.61653,1.709354,3.138163,6.034145,17.50302,15.058383
min,1.000000,40.00000,4.000000,1.000000,0.000000,35.00000,26.670000
25%,3.000000,55.00000,5.000000,3.000000,5.000000,50.00000,76.727500
50%,6.000000,70.00000,6.500000,6.000000,10.000000,65.00000,92.120000
75%,9.000000,85.00000,8.000000,9.000000,15.000000,80.00000,100.000000
max,11.000000,100.00000,9.000000,11.000000,20.000000,95.00000,100.000000

In [15]:
df.columns

Index(['study_hours', 'attendance', 'sleep_hours', 'internet_usage',
       'assignments_completed', 'previous_score', 'exam_score',
       'placement_status'],
      dtype='object')

In [16]:
df.index # gives the index range

RangeIndex(start=0, stop=10000, step=1)

In [18]:
display(df['internet_usage'] )#to read specific column


# for multiple column selection , a list needs to be given
# if it is not passed as list then error id thrown
display(df[['internet_usage','study_hours']])

# can be accessed using '.' , but not recommended
display(df.study_hours)

      internet_usage  study_hours
0                  7            7
1                  3            4
2                  6           11
3                  8            8
4                  6            5
...              ...          ...
9995               7            2
9996               9            7
9997               5           10
9998               5           10
9999              11            2

[10000 rows x 2 columns]

In [26]:
# Accessing Rows

# single row
display(df.iloc[0])

#multiple rows
display(df.iloc[0:5])

display(df.iloc[1])

study_hours                   7
attendance                   56
sleep_hours                   8
internet_usage                7
assignments_completed        10
previous_score               62
exam_score                100.0
placement_status         Placed
Name: 0, dtype: object

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed

study_hours                   4
attendance                   69
sleep_hours                   5
internet_usage                3
assignments_completed         8
previous_score               56
exam_score                100.0
placement_status         Placed
Name: 1, dtype: object

In [24]:
# All the rows that meet a specific condition
display(df.loc[df['study_hours']==11])

display(df.loc[df['study_hours']==11,['attendance','sleep_hours']])

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
2,11,60,7,6,10,45,100.00,Placed
9,11,77,4,9,15,69,100.00,Placed
10,11,64,8,8,12,76,100.00,Placed
29,11,63,9,10,1,72,96.59,Placed
30,11,45,5,2,4,93,100.00,Placed
...,...,...,...,...,...,...,...,...
9969,11,84,8,2,3,83,100.00,Placed
9971,11,81,9,6,0,85,100.00,Placed
9978,11,92,8,2,16,79,100.00,Placed
9979,11,78,9,5,18,82,100.00,Placed
9988,11,94,6,9,6,67,100.00,Placed

      attendance  sleep_hours
2             60            7
9             77            4
10            64            8
29            63            9
30            45            5
...          ...          ...
9969          84            8
9971          81            9
9978          92            8
9979          78            9
9988          94            6

[868 rows x 2 columns]

In [27]:
display(df.loc[df['study_hours']==11,['attendance','sleep_hours']].iloc[4:8])

     attendance  sleep_hours
30           45            5
91          100            9
98          100            6
116          55            7

In [28]:
display(df.loc[df['study_hours']==11]['sleep_hours'])

2       7
9       4
10      8
29      9
30      5
       ..
9969    8
9971    9
9978    8
9979    9
9988    6
Name: sleep_hours, Length: 868, dtype: int64

In [29]:
df2 = df.loc[df['study_hours']==11] # access data through label, condition, WORKS ON LABEL !!
display(df2)

display(df2.iloc[3])# access the data through index only , apni indexing par kaam karta hai, doesn't matter actual data mein vo hai ya nhi

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
2,11,60,7,6,10,45,100.00,Placed
9,11,77,4,9,15,69,100.00,Placed
10,11,64,8,8,12,76,100.00,Placed
29,11,63,9,10,1,72,96.59,Placed
30,11,45,5,2,4,93,100.00,Placed
...,...,...,...,...,...,...,...,...
9969,11,84,8,2,3,83,100.00,Placed
9971,11,81,9,6,0,85,100.00,Placed
9978,11,92,8,2,16,79,100.00,Placed
9979,11,78,9,5,18,82,100.00,Placed
9988,11,94,6,9,6,67,100.00,Placed

study_hours                  11
attendance                   63
sleep_hours                   9
internet_usage               10
assignments_completed         1
previous_score               72
exam_score                96.59
placement_status         Placed
Name: 29, dtype: object

In [32]:
display((df.loc[df['assignments_completed']==8]).iloc[1])
df[df['assignments_completed']==8].iloc[1] # the same

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [33]:
df[df["assignments_completed"]>3]

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [40]:
#ADDING A NEW COLUMN

df['age']=20
display(df)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status,age
0,7,56,8,7,10,62,100.00,Placed,20
1,4,69,5,3,8,56,100.00,Placed,20
2,11,60,7,6,10,45,100.00,Placed,20
3,8,99,9,8,4,55,90.17,Placed,20
4,5,52,8,6,8,40,78.82,Placed,20
...,...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed,20
9996,7,98,6,9,4,87,100.00,Placed,20
9997,10,44,8,5,10,37,95.94,Placed,20
9998,10,75,7,5,8,52,88.61,Placed,20
9999,2,70,6,11,16,52,78.96,Placed,20

In [49]:
#RENAMING A COLUMN
import pandas as pd
df=pd.read_csv('student_data.csv')
df = df.rename(columns={'assignments_completed':'assign_completed'}) #returning a new dataframe that needs to be stored
display(df)

,study_hours,attendance,sleep_hours,internet_usage,assign_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [50]:
# RENAMING A COLUMN IN PLACE
df.rename(columns={'assign_completed':'assignment_completed'},inplace =True)
display(df)

,study_hours,attendance,sleep_hours,internet_usage,assignment_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [56]:
# dropping rows and columns
df.drop('attendance', axis=1)

,study_hours,sleep_hours,internet_usage,assignment_completed,previous_score,exam_score,placement_status
0,7,8,7,10,62,100.00,Placed
1,4,5,3,8,56,100.00,Placed
2,11,7,6,10,45,100.00,Placed
3,8,9,8,4,55,90.17,Placed
4,5,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...
9995,2,9,7,8,88,69.31,Not Placed
9996,7,6,9,4,87,100.00,Placed
9997,10,8,5,10,37,95.94,Placed
9998,10,7,5,8,52,88.61,Placed
9999,2,6,11,16,52,78.96,Placed

In [60]:
 # dropna works for null values
dct1={
     'name':["siya","jiya","akshita"],
     'age':[None,19,19]
 }
df1=pd.DataFrame(dct1)
display(df1)
df1.dropna()

      name   age
0     siya   NaN
1     jiya  19.0
2  akshita  19.0

      name   age
1     jiya  19.0
2  akshita  19.0

In [67]:
# sort values by column
df=pd.read_csv('student_data.csv')
df=df.sort_values(by=["assignments_completed"])
display(df)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
519,3,99,8,8,0,85,85.44,Placed
516,5,68,6,6,0,35,65.59,Not Placed
498,10,71,6,4,0,57,84.82,Placed
5639,4,91,7,9,0,66,54.75,Not Placed
5623,2,95,4,6,0,45,50.30,Not Placed
...,...,...,...,...,...,...,...,...
1653,3,66,9,8,20,94,100.00,Placed
1647,8,98,4,4,20,40,100.00,Placed
4318,8,71,6,3,20,90,100.00,Placed
4642,11,85,4,11,20,53,100.00,Placed
28,1,44,9,1,20,44,76.12,Placed

In [71]:
df=df.sort_index()
display(df)

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [72]:
df.isnull()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
9995,False,False,False,False,False,False,False,False
9996,False,False,False,False,False,False,False,False
9997,False,False,False,False,False,False,False,False
9998,False,False,False,False,False,False,False,False
9999,False,False,False,False,False,False,False,False

In [73]:
df.notnull()

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...
9995,True,True,True,True,True,True,True,True
9996,True,True,True,True,True,True,True,True
9997,True,True,True,True,True,True,True,True
9998,True,True,True,True,True,True,True,True
9999,True,True,True,True,True,True,True,True

In [75]:
#replace the missing values
dct1={
     'name':["siya","jiya","akshita"],
     'age':[None,19,19]
 }
df1=pd.DataFrame(dct1)
display(df1)
df1.fillna(20)

      name   age
0     siya   NaN
1     jiya  19.0
2  akshita  19.0

      name   age
0     siya  20.0
1     jiya  19.0
2  akshita  19.0

In [76]:
# find unique values
# for a series only
df['attendance'].unique()

array([ 56,  69,  60,  99,  52,  40,  86,  72,  77,  64,  65,  98,  67,
        76,  80,  96,  88,  87,  47,  95,  51,  44,  63,  45,  71,  81,
        42,  58,  82,  68,  89,  41,  48,  85,  75, 100,  59,  43,  54,
        55,  50,  94,  93,  73,  61,  90,  66,  49,  97,  70,  84,  74,
        92,  46,  91,  83,  79,  78,  57,  62,  53])