<a href="https://colab.research.google.com/github/siyab8160-max/Data-Science/blob/main/Data_Science_08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

JOIN

-> needs two datasets

-> can be used on one dataset as well

In [ ]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Raja','Rani','Rahul','Rhea'],
    'age':[25,30,35,40]
})

df2=pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Rahul','Rhea','Ravi','Reena'],
    'age':[35,40,45,50]
})

# INNER JOIN -> fetches common values.
# pd.merge( left df, right df, common column, which join?)
df3 = pd.merge(df1,df2,on='id',how='inner')
print(df3)

# to rename the columns
df3.rename(columns={'name_x':'table1_name','name_y':'table2_name','age_x':'table1_age','age_y':'table2_age'},inplace=True)
print(df3)

   id name_x  age_x name_y  age_y
0   3  Rahul     35  Rahul     35
1   4   Rhea     40   Rhea     40
   id table1_name  table1_age table2_name  table2_age
0   3       Rahul          35       Rahul          35
1   4        Rhea          40        Rhea          40

In [ ]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Raja','Rani','Rahul','Rhea'],
    'age':[25,30,35,40]
})

df2=pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Rahul','Rhea','Ravi','Reena'],
    'age':[35,40,45,50]
})

# LEFT JOIN
# pd.merge( left df, right df, common column, which join?)
df3 = pd.merge(df1,df2,on='id',how='left')
print(df3)

   id name_x  age_x name_y  age_y
0   1   Raja     25    NaN    NaN
1   2   Rani     30    NaN    NaN
2   3  Rahul     35  Rahul   35.0
3   4   Rhea     40   Rhea   40.0

In [ ]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Raja','Rani','Rahul','Rhea'],
    'age':[25,30,35,40]
})

df2=pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Rahul','Rhea','Ravi','Reena'],
    'age':[35,40,45,50]
})

# RIGHT JOIN
# pd.merge( left df, right df, common column, which join?)
df3 = pd.merge(df1,df2,on='id',how='right')
print(df3)

   id name_x  age_x name_y  age_y
0   3  Rahul   35.0  Rahul     35
1   4   Rhea   40.0   Rhea     40
2   5    NaN    NaN   Ravi     45
3   6    NaN    NaN  Reena     50

In [ ]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Raja','Rani','Rahul','Rhea'],
    'age':[25,30,35,40]
})

df2=pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Rahul','Rhea','Ravi','Reena'],
    'age':[35,40,45,50]
})

# OUTER JOIN
# pd.merge( left df, right df, common column, which join?)
df3 = pd.merge(df1,df2,on='id',how='outer')
print(df3)

   id name_x  age_x name_y  age_y
0   1   Raja   25.0    NaN    NaN
1   2   Rani   30.0    NaN    NaN
2   3  Rahul   35.0  Rahul   35.0
3   4   Rhea   40.0   Rhea   40.0
4   5    NaN    NaN   Ravi   45.0
5   6    NaN    NaN  Reena   50.0

In [ ]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Raja','Rani','Rahul','Rhea'],
    'age':[25,30,35,40]
})

df2=pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Rahul','Rhea','Ravi','Reena'],
    'age':[35,40,45,50]
})

# CROSS JOIN -> No 'on' parameter
# pd.merge( left df, right df, common column, which join?)
df3 = pd.merge(df1, df2, how='cross')
display(df3)

    id_x name_x  age_x  id_y name_y  age_y
0      1   Raja     25     3  Rahul     35
1      1   Raja     25     4   Rhea     40
2      1   Raja     25     5   Ravi     45
3      1   Raja     25     6  Reena     50
4      2   Rani     30     3  Rahul     35
5      2   Rani     30     4   Rhea     40
6      2   Rani     30     5   Ravi     45
7      2   Rani     30     6  Reena     50
8      3  Rahul     35     3  Rahul     35
9      3  Rahul     35     4   Rhea     40
10     3  Rahul     35     5   Ravi     45
11     3  Rahul     35     6  Reena     50
12     4   Rhea     40     3  Rahul     35
13     4   Rhea     40     4   Rhea     40
14     4   Rhea     40     5   Ravi     45
15     4   Rhea     40     6  Reena     50

In [ ]:
df1=pd.DataFrame({
    'id':[1,2,3,4],
    'name':['Raja','Rani','Rahul','Rhea'],
    'age':[25,30,35,40]
})

df2=pd.DataFrame({
    'id':[3,4,5,6],
    'name':['Rahul','Rhea','Ravi','Reena'],
    'age':[35,40,45,50]
})

df3 = pd.concat([df1,df2])
display(df3)

   id   name  age
0   1   Raja   25
1   2   Rani   30
2   3  Rahul   35
3   4   Rhea   40
0   3  Rahul   35
1   4   Rhea   40
2   5   Ravi   45
3   6  Reena   50

In [ ]:
# 183 -> LEETCODE
import pandas as pd

def find_customers(customers: pd.DataFrame, orders: pd.DataFrame) -> pd.DataFrame:
    df = pd.merge(customers,orders, left_on='id', right_on='customerId', how='left')
    df = df[df['customerId'].isna()] #null values
    df = df[['name']] #filtering only names
    df = df.rename(columns={'name':'customers'}) # renaming the name column with customers
    return df

In [ ]:
# 1148 -> LEETCODE
import pandas as pd

def article_views(views: pd.DataFrame) -> pd.DataFrame:
    df = views[views['author_id']==views['viewer_id']]#filtering
    df = df[['author_id']]
    sr = df['author_id'].unique()
    df = pd.DataFrame({'id': sr})
    df.sort_values('id', inplace=True)
    return df

In [ ]:
# drop_duplicates()

# parameters in drop_duplicates()
df3=df3.drop_duplicates(subset=['id'],keep='first',inplace=False)

df3=df3.drop_duplicates(subset=['id','name'],keep='first',inplace=True) #takes both into consideration

In [ ]:
# 196 -> LEETCODE
import pandas as pd

def delete_duplicate_emails(person: pd.DataFrame) -> None:
    person.drop_duplicates(subset=['email'],keep='first',inplace=True)

In [ ]:
pd.to_datetime() # datatype for dates in pandas

PIVOT TABLE

In [13]:
import pandas as pd
df = pd.read_csv('/content/student_data.csv')

#index -> rows
df.pivot_table(columns='placement_status', index='sleep_hours', values ='exam_score', aggfunc='mean')

placement_status  Not Placed     Placed
sleep_hours
4                  59.424160  90.483113
5                  58.306079  91.085519
6                  60.971968  91.819595
7                  59.650121  92.279986
8                  60.091122  93.062072
9                  61.181129  92.987227

In [14]:
df.pivot_table(columns='study_hours', index='sleep_hours', values ='assignments_completed', aggfunc='mean')

study_hours,1,2,3,4,5,6,7,8,9,10,11
sleep_hours,,,,,,,,,,,
4,9.980392,10.283784,10.166667,9.529801,10.187050,10.530612,9.836158,10.486111,9.950000,9.114458,9.662420
5,10.231707,9.837838,10.051948,9.706667,9.679487,10.604651,11.151515,10.118519,10.616279,9.886228,9.863946
6,10.566265,10.417808,10.229299,9.694805,10.066667,10.131737,9.934307,10.601399,9.868966,9.375000,9.291045
7,11.026846,9.166667,9.440252,10.007143,9.888889,9.606250,10.750000,8.380368,11.130719,10.506024,9.741007
8,9.303448,8.741935,9.807692,10.204545,9.843373,10.105960,10.057325,9.967742,10.633987,10.060000,10.220000
9,10.245283,9.646667,9.968944,9.582822,10.308725,9.744681,10.355828,9.926667,10.085714,9.185185,10.141844

In [ ]:
# HW -> 1327
# ->511
# ->586
# ->1050
# ->175
# ->181
# ->182
# ->262
# ->185
# ->1179
# Questions related to pivot table